# SPDX-License-Identifier: GPL-2.0


snd-soc-mx-i2s-objs      := mx_i2s.o
snd-soc-axi-dma-objs      := axi_dma.o
snd-mikroe-proto-objs      := mikroe-proto.o
#obj-$(SND_SIMPLE_I2S) += snd-soc-mx-i2s.o
#obj-$(SND_SIMPLE_I2S) += snd-soc-axi-dma.o

obj-y += snd-soc-mx-i2s.o
obj-y += snd-soc-axi-dma.o
obj-y += snd-mikroe-proto.o

